name: Generate Integration Test Buckets

on:
  schedule:
    - cron: "0 1 * * 3" # Every Wed at 1AM
  workflow_dispatch:

jobs:
  bucket-generator:
    name: bucket generator
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Setup VM for cifuzz
        uses: ./.github/actions/vm_setup
        with:
          os: ubuntu-22.04

      - name: Run integration go test and collect JSON in file
        run: make test/integration

      # Upload the original go test log as an artifact for later review.
      - name: Upload test log
        uses: actions/upload-artifact@v2
        with:
          name: test-log
          path: gotest.log
          if-no-files-found: error

      - name: Run bucket generator
        run: go run tools/test-bucket-generator/bucket.go

      - name: Create a PR with new bucket data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER_OF_BUCKETS: ${{ vars.NUMBER_OF_BUCKETS }}
        run: |
          gh auth setup-git
          git config --global user.email "cifuzz@code-intelligence.com"
          git config --global user.name "$GITHUB_ACTOR"
          git checkout -b test/update-buckets
          git add tools/test-bucket-generator
          git commit -m "test: update integration test timing buckets"
          git push --force --set-upstream origin test/update-buckets
          gh pr create --title="Test: Fresh buckets for integration tests" --body="Automatic bucket rebalancer" --head test/fresh-buckets
