name: PR Pipeline

on:
  merge_group:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  no-wip-commits:
    name: No WIP, fixup or XXX commits
    runs-on: ubuntu-22.04

    steps:
      - name: Check Commit Messages
        # we can skip this check on merge groups (it is also not supported by the used action)
        if: ${{ github.event_name != 'merge_group' }}
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(?!WIP|XXX|fixup).*'
          error: 'A commit message should not start with (WIP|XXX|fixup)'
          excludeDescription: true
          checkAllCommitMessages: true
          accessToken: ${{ secrets.GITHUB_TOKEN }}
